server:
  context-path: /public
  port: 8095

logging:
  level:
    project:
      user:
        UserClient: DEBUG
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://REGISTRY-SERVER:${REGISTRY_SERVER_PORT}/eureka/
spring:
  datasource:
    url: jdbc:mysql://S_MYSQL_SERVER:${S_MYSQL_SERVER_PORT}/yimym?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: ${S_MYSQL_SERVER_USER}
    password: ${S_MYSQL_SERVER_PASS}
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 30000
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect        
        
multipart:
  maxFileSize: 300Mb
  maxRequestSize: 300Mb
yimym:
  pageable:
    defaultPageSize: 10
  file:
    path: /yimym/data/
  mysqlBackup:
    path: /yimym/mysqlBackup/
  logofile:
    path: /yimym/logo.png
