package com.cdc.workcloud.manage.domain.sys;

// Generated 2015-11-29 9:59:36 by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SysLoginLog generated by hbm2java
 */
@Entity
@Table(name = "sys_login_log"
)
public class SysLoginLog implements java.io.Serializable {


    private Long id;
    private String userCode;
    private String userName;
    private String operateType;
    private String ipAddress;
    private Date operateTime;
    private Long isdel;
    private String sessionId;

    public SysLoginLog() {
    }

    public SysLoginLog(String userCode, Date operateTime) {
        this.userCode = userCode;
        this.operateTime = operateTime;
    }

    public SysLoginLog(String userCode, String userName, String operateType,String ipAddress
            ,Date operateTime,Long isdel) {
        this.userCode = userCode;
        this.userName = userName;
        this.operateType = operateType;
        this.ipAddress = ipAddress;
        this.operateTime = operateTime;
        this.isdel = isdel;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "user_code", length = 50)
    public String getUserCode() {
        return this.userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    @Column(name = "user_name", length = 256)
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "operate_type", length = 256)
    public String getOperateType() {
        return operateType;
    }

    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    @Column(name = "ip_address", length = 256)
    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "operate_time", nullable = false, length = 19)
    public Date getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    @Column(name = "isdel")
    public Long getIsdel() {
        return isdel;
    }

    public void setIsdel(Long isdel) {
        this.isdel = isdel;
    }

    @Column(name = "session_id")
    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
}


